version: "3.8"
services:
  servers:
    build: 
      context: ./
      dockerfile: Dockerfile
      args:
        STAGE: ${STAGE:-dev}
      target: ${TARGET:-appWebServerRuntime}
    image: danijelradakovic/servers:${VERSION:-1.1.0}-${STAGE:-dev}
    container_name: servers
    restart: on-failure
    networks:
      - backend
      - database
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DOMAIN: ${DATABASE_DOMAIN}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      KEYSTORE: ${KEYSTORE}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
      KEYSTORE_ALIAS: ${KEYSTORE_ALIAS}
      TRUSTSTORE: ${TRUSTSTORE}
      TRUSTSTORE_PASSWORD: ${TRUSTSTORE_PASSWORD}
      RMQ_HOST: ${MESSAGE_BROKER}
      RMQ_PORT: ${RMQ_PORT}
    volumes:
      - ${KEYSTORE_PATH}:/etc/keystore
    depends_on: 
      - database
      - message-broker
    
  database:
    image: mysql:${MYSQL_VERSION:-8.0.19}
    container_name: mysql
    restart: always
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - database-data:/var/lib/mysql

  message-broker:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-broker
    ports:
      - 15671:15671
    networks:
      - backend
    environment:
      RABBITMQ_SSL_CACERTFILE: ${RABBITMQ_SSL_CACERTFILE}
      RABBITMQ_SSL_CERTFILE: ${RABBITMQ_SSL_CERTFILE}
      RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: ${RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT}
      RABBITMQ_SSL_KEYFILE: ${RABBITMQ_SSL_KEYFILE}
      RABBITMQ_SSL_VERIFY: ${RABBITMQ_SSL_VERIFY}
    volumes:
      - ${RABBITMQ_KEYSTORE_PATH}:/etc/rabbitmq/cert

volumes:
  database-data:
    name: server-database

networks:
  backend:
    name: backend
    driver: bridge
  database:
    name: database
    driver: bridge
