version: "3.8"
services:
  servers:
    build: 
      context: ./
      dockerfile: Dockerfile
      args:
        STAGE: ${STAGE:-dev}
      target: ${TARGET:-appWebServerRuntime}
    image: danijelradakovic/servers:${VERSION:-1.0.0}-${STAGE:-dev}
    container_name: servers
    restart: on-failure
    networks:
      - backend
      - database
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DOMAIN: ${DATABASE_DOMAIN}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      RMQ_HOST: ${MESSAGE_BROKER}
    depends_on: 
      - database
      - message-broker
    
  database:
    image: mysql:${MYSQL_VERSION:-8.0.19}
    container_name: mysql
    restart: always
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - database-data:/var/lib/mysql

  message-broker:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-broker
    ports:
      - 15672:15672
    networks:
      - backend

volumes:
  database-data:
    name: server-database

networks:
  backend:
    name: backend
    driver: bridge
  database:
    name: database
    driver: bridge
